### ISSUE TITLE
Exception thrown when setting up the MicroStream MariaDB driver 

### ISSUE THREAD

**Issue by WaveBleak** [Aelysium-Group/rusty-connector#57]
My server is running the latest version of velocity and your plugin as the only plugin installed. I have attached my logs folder.
[latest.log](https://github.com/Aelysium-Group/rusty-connector/files/13784839/latest.log)

I've tried setting up the plugin on two different computers(one running linux and another running windows), both fail when booting the plugin. Here is the stacktrace:

```
[08:43:31 ERROR]: java.lang.RuntimeException: one.microstream.afs.exceptions.AfsException
[08:43:31 ERROR]:       at group.aelysium.rustyconnector.plugin.velocity.central.Flame.fabricateNew(Flame.java:181)
[08:43:31 ERROR]:       at group.aelysium.rustyconnector.plugin.velocity.central.Tinder.ignite(Tinder.java:48)
[08:43:31 ERROR]:       at group.aelysium.rustyconnector.plugin.velocity.VelocityRustyConnector.onLoad(VelocityRustyConnector.java:39)[08:43:31 ERROR]:       at group.aelysium.rustyconnector.plugin.velocity.Lmbda$2.execute(Unknown Source)
[08:43:31 ERROR]:       at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56)
[08:43:31 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597)
[08:43:31 ERROR]:       at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478)
[08:43:31 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
[08:43:31 ERROR]:       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
[08:43:31 ERROR]:       at java.base/java.lang.Thread.run(Thread.java:833)
[08:43:31 ERROR]: Caused by: one.microstream.afs.exceptions.AfsException
[08:43:31 ERROR]:       at one.microstream.afs.sql.types.SqlProvider$Abstract.execute(SqlProvider.java:410)
[08:43:31 ERROR]:       at one.microstream.afs.sql.types.SqlConnector$Default.directoryExists(SqlConnector.java:709)
[08:43:31 ERROR]:       at one.microstream.afs.sql.types.SqlIoHandler$Default.subjectDirectoryExists(SqlIoHandler.java:142)
[08:43:31 ERROR]:       at one.microstream.afs.sql.types.SqlIoHandler$Default.specificExists(SqlIoHandler.java:166)
[08:43:31 ERROR]:       at one.microstream.afs.types.AIoHandler$Abstract.exists(AIoHandler.java:553)
[08:43:31 ERROR]:       at one.microstream.afs.types.AIoHandler$Abstract.ensureExists(AIoHandler.java:705)
[08:43:31 ERROR]:       at one.microstream.afs.types.ADirectory.ensureExists(ADirectory.java:70)
[08:43:31 ERROR]:       at one.microstream.storage.types.StorageFileProvider$Abstract.defineTypeDictionaryFile(StorageFileProvider.java:355)
[08:43:31 ERROR]:       at one.microstream.persistence.types.PersistenceTypeDictionaryIoHandler$Provider$Abstract.provideTypeDictionaryIoHandler(PersistenceTypeDictionaryIoHandler.java:80)
[08:43:31 ERROR]:       at one.microstream.storage.embedded.types.EmbeddedStorage.ConnectionFoundation(EmbeddedStorage.java:98)
[08:43:31 ERROR]:       at one.microstream.storage.embedded.types.EmbeddedStorageFoundation$Default.ensureConnectionFoundation(EmbeddedStorageFoundation.java:462)
[08:43:31 ERROR]:       at one.microstream.storage.embedded.types.EmbeddedStorageFoundation$Default.getConnectionFoundation(EmbeddedStorageFoundation.java:500)
[08:43:31 ERROR]:       at one.microstream.storage.embedded.types.EmbeddedStorageFoundation$Default.createEmbeddedStorageManager(EmbeddedStorageFoundation.java:789)
[08:43:31 ERROR]:       at one.microstream.storage.embedded.types.EmbeddedStorage.createAndStartStorageManager(EmbeddedStorage.java:613)
[08:43:31 ERROR]:       at one.microstream.storage.embedded.types.EmbeddedStorage.start(EmbeddedStorage.java:501)
[08:43:31 ERROR]:       at group.aelysium.rustyconnector.plugin.velocity.lib.storage.MySQLStorage.<init>(MySQLStorage.java:40)
[08:43:31 ERROR]:       at group.aelysium.rustyconnector.plugin.velocity.lib.storage.MySQLStorage.create(MySQLStorage.java:79)
[08:43:31 ERROR]:       at group.aelysium.rustyconnector.plugin.velocity.central.Initialize.connectors(Flame.java:329)
[08:43:31 ERROR]:       at group.aelysium.rustyconnector.plugin.velocity.central.Flame.fabricateNew(Flame.java:144)
[08:43:31 ERROR]:       ... 9 more
[08:43:31 ERROR]: Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=0.0.0.0)(port=3306)(type=master) : Socket fail to connect to host:0.0.0.0, port:3306. Connection refused
[08:43:31 ERROR]:       at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
[08:43:31 ERROR]:       at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:153)
[08:43:31 ERROR]:       at org.mariadb.jdbc.MariaDbDataSource.getConnection(MariaDbDataSource.java:277)
[08:43:31 ERROR]:       at one.microstream.afs.sql.types.SqlProvider$Abstract.execute(SqlProvider.java:390)
[08:43:31 ERROR]:       ... 27 more
[08:43:31 ERROR]: Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to address=(host=0.0.0.0)(port=3306)(type=master) : Socket fail to connect to host:0.0.0.0, port:3306. Connection refused
[08:43:31 ERROR]:       at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
[08:43:31 ERROR]:       at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:192)
[08:43:31 ERROR]:       at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1392)
[08:43:31 ERROR]:       at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:635)
[08:43:31 ERROR]:       at org.mariadb.jdbc.MariaDbConnection.newConnection(MariaDbConnection.java:150)
[08:43:31 ERROR]:       at org.mariadb.jdbc.MariaDbDataSource.getConnection(MariaDbDataSource.java:275)
[08:43:31 ERROR]:       ... 28 more
[08:43:31 ERROR]: Caused by: java.sql.SQLNonTransientConnectionException: Socket fail to connect to host:0.0.0.0, port:3306. Connection refused
[08:43:31 ERROR]:       at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:73)
[08:43:31 ERROR]:       at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:183)
[08:43:31 ERROR]:       at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createSocket(AbstractConnectProtocol.java:255)
[08:43:31 ERROR]:       at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createConnection(AbstractConnectProtocol.java:519)
[08:43:31 ERROR]:       at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:1387)
[08:43:31 ERROR]:       ... 31 more
[08:43:31 ERROR]: Caused by: java.net.ConnectException: Connection refused
[08:43:31 ERROR]:       at java.base/sun.nio.ch.Net.pollConnect(Native Method)
[08:43:31 ERROR]:       at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
[08:43:31 ERROR]:       at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:542)
[08:43:31 ERROR]:       at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597)
[08:43:31 ERROR]:       at java.base/java.net.SocksSocketImpl.connect(
SocksSocketImpl.java:327)
[08:43:31 ERROR]:       at java.base/java.net.Socket.connect(Socket.java:633)
[08:43:31 ERROR]:       at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.createSocket(AbstractConnectProtocol.java:250)
[08:43:31 ERROR]:       ... 33 more```

**Comment by nathan-i-martin** [comment]
This is expected behavior and not a bug.
The support conversation has been moved to Discord.
