### ISSUE TITLE
SQL syntax error

### ISSUE THREAD

**Issue by mrsqueak11806** [Aelysium-Group/rusty-connector#72]
# 🐞 I found a bug

I'm using MySQL version 8.4.0

[20:22:44 ERROR]: java.sql.SQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'schema VARCHAR(32) NOT NULL,    rank VARCHAR(256) NOT NULL,    FOREIGN KEY (play' at line 1
[20:22:44 ERROR]: 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:121)
[20:22:44 ERROR]: 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
[20:22:44 ERROR]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:916)
[20:22:44 ERROR]: 	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:354)
[20:22:44 ERROR]: 	at group.aelysium.rustyconnector.plugin.velocity.lib.storage.reactors.MySQLReactor$Core.execute(MySQLReactor.java:419)
[20:22:44 ERROR]: 	at group.aelysium.rustyconnector.plugin.velocity.lib.storage.reactors.MySQLReactor.initializeDatabase(MySQLReactor.java:70)
[20:22:44 ERROR]: 	at group.aelysium.rustyconnector.plugin.velocity.lib.storage.reactors.MySQLReactor.<init>(MySQLReactor.java:61)
[20:22:44 ERROR]: 	at group.aelysium.rustyconnector.plugin.velocity.lib.storage.StorageService$StorageConfiguration$MySQL.reactor(StorageService.java:58)
[20:22:44 ERROR]: 	at group.aelysium.rustyconnector.plugin.velocity.lib.storage.StorageService.<init>(StorageService.java:16)
[20:22:44 ERROR]: 	at group.aelysium.rustyconnector.plugin.velocity.lib.storage.StorageService.create(StorageService.java:29)
[20:22:44 ERROR]: 	at group.aelysium.rustyconnector.plugin.velocity.central.Initialize.connectors(Flame.java:339)
[20:22:44 ERROR]: 	at group.aelysium.rustyconnector.plugin.velocity.central.Flame.fabricateNew(Flame.java:144)
[20:22:44 ERROR]: 	at group.aelysium.rustyconnector.plugin.velocity.central.Tinder.ignite(Tinder.java:51)
[20:22:44 ERROR]: 	at group.aelysium.rustyconnector.plugin.velocity.central.Tinder.rekindle(Tinder.java:78)
[20:22:44 ERROR]: 	at group.aelysium.rustyconnector.plugin.velocity.central.Reload.lambda$build$0(CommandRusty.java:400)
[20:22:44 ERROR]: 	at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262)
[20:22:44 ERROR]: 	at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:230)
[20:22:44 ERROR]: 	at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeAsync$0(VelocityCommandManager.java:268)
[20:22:44 ERROR]: 	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
[20:22:44 ERROR]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
[20:22:44 ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20:22:44 ERROR]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20:22:44 ERROR]: 	at java.base/java.lang.Thread.run(Unknown Source)
[20:22:44 INFO]:  Initializing 30%... 
[20:22:44 INFO]:  Initializing 40%... 
[20:22:44 INFO]:  Initializing 50%... 
[20:22:44 INFO]:  Initializing 60%... 
[20:22:44 INFO]:  Initializing 70%... 
[20:22:44 INFO]:  Initializing 80%... 
[20:22:44 INFO]:  Initializing 90%... 
[20:22:44 INFO]:  Initializing 100%... 
[20:22:44 INFO] [rustyconnector-velocity]: Done reloading!

## 🔍 Steps to Reproduce
> Steps to reproduce the behavior:

1. Go to '...' ✍
2. Interact with '....' ✍
3. Perform action '....' ✍
4. See unexpected behavior 😕 ✍

## 💻 Environment and RC versions

* RC Version: ✍
* Java version: 17 

* Velocity version: ✍
* Server Software Version: ✍

## 💡 Possible Solution

I think that...

## 📝 Logs

Debug link: ✍ 

```error
ERROR
```

**Comment by nathan-i-martin** [comment]
Currently fixed in dev builds. (Keep an eye out for v0.8.1)
